/* Dashboard PCFI */
(function(){
  'use strict';
  var cfg=window.PCFI_CONFIG||{},state={pedidos:[],pedido:null,pcfi:null,etapa:'',pcfis:[],itens:[],itensAll:[],itensPcfi:[],paginaPedidos:1,pedidosPorPagina:20,pedidosFiltrados:[],confirmacaoAberta:false,cameraStream:null,cameraItem:-1,cameraOpener:null,modalAberto:null,modalRetorno:null,modalEscape:null,modalKeydown:null,modalOverflow:null,modalOverscroll:'',toastTimer:null};
  var $=function(id){return document.getElementById(id)};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function n(v){var x=Number(String(v==null?'':v).replace(',','.'));return isFinite(x)?x:0}
  function fmt(v){return n(v).toLocaleString('pt-BR',{minimumFractionDigits:0,maximumFractionDigits:4})}
  function isoDate(v){var m=String(v||'').match(/^(\d{4}-\d{2}-\d{2})/);if(m)return m[1];m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:''}
  function sqlDate(v){var d=isoDate(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(d))throw new Error('Data de filtro inválida.');return d}
  function loading(on,text){var el=$('loading');el.hidden=!on;el.classList.toggle('hidden',!on);el.setAttribute('aria-busy',on?'true':'false');$('loadingText').textContent=text||'Carregando…'}
  function toast(msg,error){var el=$('toast');if(state.toastTimer)window.clearTimeout(state.toastTimer);el.hidden=false;el.className='toast'+(error?' error':'');el.setAttribute('role',error?'alert':'status');el.setAttribute('aria-live',error?'assertive':'polite');el.setAttribute('aria-atomic','true');el.textContent='';el.textContent=String(msg||'');state.toastTimer=window.setTimeout(function(){el.hidden=true;el.classList.add('hidden');state.toastTimer=null},5000)}
  function focaveis(modal){return Array.prototype.filter.call(modal.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])'),function(el){return !el.disabled&&el.getAttribute('aria-hidden')!=='true'&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length)})}
  function abrirModalAcessivel(modal,retorno,inicial,aoEsc){
    state.modalAberto=modal;state.modalRetorno=retorno;state.modalEscape=aoEsc;state.modalOverflow={html:document.documentElement.style.overflow,body:document.body.style.overflow};state.modalOverscroll=modal.style.overscrollBehavior;document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';modal.style.overscrollBehavior='contain';
    state.modalKeydown=function(e){if(state.modalAberto!==modal)return;if(e.key==='Escape'){e.preventDefault();if(state.modalEscape)state.modalEscape();return}if(e.key!=='Tab')return;var lista=focaveis(modal);if(!lista.length){e.preventDefault();if(modal.focus)modal.focus();return}if(!modal.contains(document.activeElement)){e.preventDefault();(e.shiftKey?lista[lista.length-1]:lista[0]).focus();return}var primeiro=lista[0],ultimo=lista[lista.length-1];if(e.shiftKey&&document.activeElement===primeiro){e.preventDefault();ultimo.focus()}else if(!e.shiftKey&&document.activeElement===ultimo){e.preventDefault();primeiro.focus()}};
    document.addEventListener('keydown',state.modalKeydown,true);var alvo=inicial||focaveis(modal)[0];if(alvo&&alvo.focus)alvo.focus()
  }
  function fecharModalAcessivel(restaurar){var modal=state.modalAberto;if(!modal)return;document.removeEventListener('keydown',state.modalKeydown,true);modal.style.overscrollBehavior=state.modalOverscroll;document.documentElement.style.overflow=state.modalOverflow.html;document.body.style.overflow=state.modalOverflow.body;var retorno=state.modalRetorno;state.modalAberto=null;state.modalRetorno=null;state.modalEscape=null;state.modalKeydown=null;state.modalOverflow=null;if(restaurar!==false&&retorno&&document.documentElement.contains(retorno)&&!retorno.disabled)retorno.focus()}
  function confirmar(titulo,mensagem,rotuloConfirmar){
    if(state.confirmacaoAberta)return Promise.resolve(false);state.confirmacaoAberta=true;
    var modal=$('modalConfirmacao'),btnConfirmar=$('btnConfirmacaoConfirmar'),btnCancelar=$('btnConfirmacaoCancelar'),ativo=document.activeElement;
    $('modalConfirmacaoTitulo').textContent=titulo||'Confirmar ação';$('modalConfirmacaoMensagem').textContent=mensagem||'Deseja continuar?';btnConfirmar.textContent=rotuloConfirmar||'Confirmar';
    modal.hidden=false;modal.classList.remove('hidden');
    return new Promise(function(resolve){
      var encerrado=false;
      function fechar(confirmado){if(encerrado)return;encerrado=true;state.confirmacaoAberta=false;modal.hidden=true;modal.classList.add('hidden');btnConfirmar.onclick=null;btnCancelar.onclick=null;modal.onclick=null;fecharModalAcessivel(true);resolve(confirmado)}
      btnConfirmar.onclick=function(){fechar(true)};btnCancelar.onclick=function(){fechar(false)};
      modal.onclick=function(e){if(e.target===modal)fechar(false)};abrirModalAcessivel(modal,ativo,btnConfirmar,function(){fechar(false)});
    });
  }
  function post(url,body){
    return fetch(url,{method:'POST',credentials:'same-origin',redirect:'follow',headers:{'Content-Type':'application/json;charset=UTF-8'},body:JSON.stringify(body)})
      .then(function(r){return r.json()});
  }
  function apiSave(campos,entidade,pk,returnFields){
    var localFields={},fieldNames=Object.keys(campos);
    (returnFields||[]).forEach(function(field){if(fieldNames.indexOf(field)<0)fieldNames.push(field)});
    fieldNames.forEach(function(key){var value=campos[key];if(value!==null&&value!==undefined&&value!=='')localFields[key.toUpperCase()]={$:String(value)}});
    var dataRow={localFields:localFields};
    if(pk){dataRow.key={};Object.keys(pk).forEach(function(key){dataRow.key[key.toUpperCase()]={$:String(pk[key])}})}
    var body={serviceName:'CRUDServiceProvider.saveRecord',requestBody:{dataSet:{rootEntity:entidade,includePresentationFields:'N',dataRow:dataRow,entity:{fieldset:{list:fieldNames.map(function(k){return k.toUpperCase()}).join(',')}}}}};
    var url=window.location.origin+'/mge/service.sbr?serviceName=CRUDServiceProvider.saveRecord&outputType=json';
    return post(url,body).then(function(data){
      if(String(data.status)!=='1')throw new Error(data.statusMessage||(data.responseBody&&data.responseBody.message)||('Falha ao salvar '+entidade));
      var entity=data.responseBody&&data.responseBody.entities&&data.responseBody.entities.entity;
      if(Array.isArray(entity))entity=entity[0];
      if(!entity)throw new Error('O Sankhya não devolveu a entidade gravada em '+entidade+'.');
      var result={};Object.keys(entity).forEach(function(key){result[key]=entity[key]&&entity[key].$!==undefined?entity[key].$:entity[key]});
      return result;
    });
  }
  window.saveRecords=apiSave;

  function carregarPedidos(){
    loading(true,'Lendo pedidos pendentes...');
    try{
      state.pedidos=Array.prototype.map.call(document.querySelectorAll('#data-pedidos .data-pedido'),function(el){var d=el.dataset;return {NUNOTA:d.nunota,NUMNOTA:d.numnota,DTNEG:d.dtneg,CODEMP:d.codemp,CODPARC:d.codparc,NOMEPARC:d.nomeparc,CODCENCUS:d.codcencus,DESCRCR:d.descrCr,QTD_ITENS:d.qtdItens,QTD_PENDENTE:d.qtdPendente,QTD_PCFI:d.qtdPcfi,QUALPELCONF:d.qualpelconf,CODUSULOGADO:d.codusuLogado,PODEPRIORIDADE:d.podePrioridade,PODEQTDE:d.podeQtde,PODEQUAL:d.podeQual,PODEFISC:d.podeFisc,STATUSOC:d.statusOc,STATUSCOR:d.statusCor}});
      state.pcfis=Array.prototype.map.call(document.querySelectorAll('#data-pcfis .data-pcfi'),function(el){var d=el.dataset;return {NUPCFI:d.nupcfi,NUNOTAOC:d.nunotaoc,NUMNOTANF:d.numnotanf,STATUSPCFI:d.statuspcfi,STATUSQUAL:d.statusqual,STATUSFISCAL:d.statusfiscal,PRIORIDADE:d.prioridade,ENTREGAPARCIAL:d.entregaparcial,OBSERVACAO:d.observacao}});
      state.itensAll=Array.prototype.map.call(document.querySelectorAll('#data-itens .data-item'),function(el){var d=el.dataset;return {NUNOTA:d.nunota,SEQUENCIA:d.sequencia,CODPROD:d.codprod,DESCRPROD:d.descrprod,CODVOL:d.codvol,QTDNEG:d.qtdneg,QTDPENDENTE:d.qtdpendente,QTDENTREGUE:d.qtdentregue,OBSERVACAO:d.observacao}});
      state.itensPcfi=Array.prototype.map.call(document.querySelectorAll('#data-itens-pcfi .data-item-pcfi'),function(el){var d=el.dataset;return {NUPCFI:d.nupcfi,SEQPCFIITEM:d.seqpcfiitem,NUNOTA:d.nunota,SEQUENCIA:d.sequencia,CODPROD:d.codprod,QTDRECEBIDA:d.qtdrecebida,IMPROPRIO:d.improprio,QTDIMPROPRIA:d.qtdimpropria,DIVERGENCIA:d.divergencia,EMBALAGEM:d.embalagem,MATERIAPRIMA:d.materiaprima,BEM:d.bem,OBSERVACAOPCFI:d.observacao}});
      state.paginaPedidos=1;state.pedidosFiltrados=state.pedidos;renderPedidos(state.pedidosFiltrados);
    }catch(e){toast('Não foi possível carregar os pedidos: '+(e.message||e),true)}finally{loading(false)}
  }
  function etapaPcfi(p){if(p.STATUSPCFI==='Q')return 'QUAL';if(p.STATUSPCFI==='F')return 'FISC';return ''}
  function podeEtapa(pedido,etapa){return etapa==='QUAL'?pedido.PODEQUAL==='S':etapa==='FISC'?pedido.PODEFISC==='S':pedido.PODEQTDE==='S'}
  function classePcfi(p){if(p.PRIORIDADE==='S'&&p.STATUSPCFI!=='C'&&p.STATUSPCFI!=='N')return ' pcfi-prioridade';if(p.STATUSPCFI==='N')return ' pcfi-negada';if(p.STATUSPCFI==='F')return ' pcfi-qual';if(p.STATUSPCFI==='Q')return ' pcfi-qtde';return ''}
  function renderPedidos(rows){
    var totalPaginas=Math.max(1,Math.ceil(rows.length/state.pedidosPorPagina));if(state.paginaPedidos>totalPaginas)state.paginaPedidos=totalPaginas;
    var inicio=(state.paginaPedidos-1)*state.pedidosPorPagina,pagina=rows.slice(inicio,inicio+state.pedidosPorPagina),body=$('pedidosBody');
    body.innerHTML=pagina.map(function(r,i){var fornecedor=String(r.CODPARC)+' - '+String(r.NOMEPARC),centro=String(r.DESCRCR||'');return '<tr class="oc-'+String(r.STATUSCOR||'').toLowerCase()+'" data-i="'+(inicio+i)+'"><td><strong>'+esc(r.NUMNOTA||r.NUNOTA)+'</strong><br><small>#'+esc(r.NUNOTA)+'</small></td><td>'+esc(r.DTNEG)+'</td><td>'+esc(r.CODEMP)+'</td><td><span class="fornecedor" title="'+esc(fornecedor)+'" aria-label="Fornecedor: '+esc(fornecedor)+'">'+esc(fornecedor.slice(0,40))+'</span></td><td><span class="centro-resultado" title="'+esc(centro)+'" aria-label="Centro de resultado: '+esc(centro)+'">'+esc(centro)+'</span></td><td>'+fmt(r.QTD_PENDENTE)+'</td><td><span class="badge">'+esc(r.STATUSOC)+'</span></td><td><button class="btn btn-secondary abrir-pedido" type="button" data-pedido-i="'+(inicio+i)+'">Abrir PCFIs</button></td></tr>'}).join('');
    var listaVazia=$('listaVazia'),termo=$('buscaPedidos').value.trim();listaVazia.innerHTML='';if(rows.length){listaVazia.classList.add('hidden')}else{var mensagem=document.createElement('p');mensagem.textContent=termo?'Nenhum pedido corresponde a "'+termo+'".':'Nenhum pedido pendente encontrado.';listaVazia.appendChild(mensagem);if(termo){var limpar=document.createElement('button');limpar.className='btn btn-secondary';limpar.type='button';limpar.textContent='Limpar busca';limpar.onclick=function(){$('buscaPedidos').value='';state.paginaPedidos=1;state.pedidosFiltrados=state.pedidos;renderPedidos(state.pedidosFiltrados)};listaVazia.appendChild(limpar)}listaVazia.classList.remove('hidden')}$('sumPedidos').textContent=rows.length;$('sumItens').textContent=state.itensAll.length;$('sumQtd').textContent=fmt(rows.reduce(function(a,r){return a+n(r.QTD_PENDENTE)},0));$('paginacaoPedidos').hidden=rows.length<=state.pedidosPorPagina;$('paginaPedidos').textContent='Página '+state.paginaPedidos+' de '+totalPaginas;$('btnPaginaAnterior').disabled=state.paginaPedidos===1;$('btnProximaPagina').disabled=state.paginaPedidos===totalPaginas;
    Array.prototype.forEach.call(body.querySelectorAll('.abrir-pedido'),function(btn){btn.onclick=function(){abrirPedido(rows[Number(btn.dataset.pedidoI)])}})
  }
  function contexto(id){$(id).innerHTML=[['Nro. único',state.pedido.NUNOTA],['Fornecedor',state.pedido.CODPARC+' - '+state.pedido.NOMEPARC],['Centro de resultado',state.pedido.DESCRCR]].map(function(x){return '<div><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>'}).join('')}
  function abrirPedido(pedido){state.pedido=pedido;cfg.codUsu=pedido.CODUSULOGADO;state.pcfi=null;state.etapa='';$('viewLista').hidden=true;$('viewLista').classList.add('hidden');$('viewPcfis').hidden=false;$('viewPcfis').classList.remove('hidden');$('viewConferencia').hidden=true;$('viewConferencia').classList.add('hidden');$('btnVoltar').hidden=false;$('btnVoltar').classList.remove('hidden');$('btnAtualizar').classList.add('hidden');$('pageTitle').textContent='PCFIs da OC '+(pedido.NUMNOTA||pedido.NUNOTA);$('pageSubtitle').textContent='Selecione uma PCFI existente ou registre uma nova chegada.';contexto('ocContextPcfis');renderPcfis()}
  function renderPcfis(){var pcfis=state.pcfis.filter(function(p){return String(p.NUNOTAOC)===String(state.pedido.NUNOTA)}),html='';if(state.pedido.PODEQTDE==='S'&&n(state.pedido.QTD_PENDENTE)>0)html+='<div class="pcfi-row"><div><strong>Nova PCFI</strong><p>Saldo operacional: '+fmt(state.pedido.QTD_PENDENTE)+'</p></div><button class="btn btn-primary" data-nova-pcfi="S" type="button">Conferir quantidade</button></div>';pcfis.forEach(function(p,i){var etapa=etapaPcfi(p),pode=podeEtapa(state.pedido,etapa),status=p.ENTREGAPARCIAL==='S'?'PCFI Parcial · ':'';status+=p.STATUSPCFI==='N'?'Negada':etapa==='QUAL'?'Aguardando Qualidade':etapa==='FISC'?'Aguardando Fiscal':'Concluída';var prioridade=state.pedido.PODEPRIORIDADE==='S'&&p.PRIORIDADE!=='S'&&p.STATUSPCFI!=='C'&&p.STATUSPCFI!=='N'?'<button class="btn btn-secondary" data-prioridade-i="'+i+'" type="button">Solicitar prioridade</button>':'';html+='<div class="pcfi-row'+classePcfi(p)+'"><div><strong>PCFI #'+esc(p.NUPCFI)+'</strong><p>NF: '+esc(p.NUMNOTANF)+' · '+status+(p.ENTREGAPARCIAL==='S'?' · Parcial':'')+'</p></div>'+(etapa&&pode?'<button class="btn btn-secondary" data-pcfi-i="'+i+'" type="button">Abrir '+(etapa==='QUAL'?'qualidade':'fiscal')+'</button>':'<span class="badge">'+esc(status)+'</span>')+prioridade+'</div>'});$('pcfisContainer').innerHTML=html||'<div class="empty">Nenhuma PCFI disponível para este usuário.</div>';var nova=$('pcfisContainer').querySelector('[data-nova-pcfi]');if(nova)nova.onclick=abrirNovaPcfi;Array.prototype.forEach.call($('pcfisContainer').querySelectorAll('[data-pcfi-i]'),function(b){b.onclick=function(){abrirPcfi(pcfis[Number(b.dataset.pcfiI)])}});Array.prototype.forEach.call($('pcfisContainer').querySelectorAll('[data-prioridade-i]'),function(b){b.onclick=function(){solicitarPrioridade(pcfis[Number(b.dataset.prioridadeI)])}})}
  async function solicitarPrioridade(pcfi){if(!await confirmar('Solicitar prioridade','Deseja solicitar prioridade para esta PCFI?','Solicitar prioridade'))return;loading(true,'Solicitando prioridade...');try{await apiSave({PRIORIDADE:'S'},'AD_PCFI',{NUPCFI:pcfi.NUPCFI});toast('Prioridade solicitada.');window.setTimeout(function(){window.location.reload()},900)}catch(e){toast('Falha ao solicitar prioridade: '+(e.message||e),true)}finally{loading(false)}}
  function valorSalvo(valor,padrao){return valor===undefined||valor===null||valor===''?padrao:valor}
  function prepararItens(base,salvos){return base.map(function(r){var antigo=salvos.filter(function(x){return String(x.SEQUENCIA)===String(r.SEQUENCIA)})[0]||{};return Object.assign({},r,antigo,{QTDRECEBIDA:valorSalvo(antigo.QTDRECEBIDA,''),IMPROPRIO:valorSalvo(antigo.IMPROPRIO,'N'),QTDIMPROPRIA:valorSalvo(antigo.QTDIMPROPRIA,0),DIVERGENCIA:valorSalvo(antigo.DIVERGENCIA,'N'),EMBALAGEM:valorSalvo(antigo.EMBALAGEM,'I'),MATERIAPRIMA:valorSalvo(antigo.MATERIAPRIMA,'N'),BEM:valorSalvo(antigo.BEM,'N'),OBSERVACAOPCFI:valorSalvo(antigo.OBSERVACAOPCFI,''),foto:null,fotoPreview:'',lotes:[],patrimonios:[]})})}
  function abrirNovaPcfi(){if(!podeEtapa(state.pedido,'QTDE')){toast('Você não está configurado para realizar a etapa de quantidade.',true);return}state.pcfi=null;state.etapa='QTDE';state.itens=prepararItens(state.itensAll.filter(function(r){return String(r.NUNOTA)===String(state.pedido.NUNOTA)}),[]);mostrarConferencia();renderItens()}
  function abrirPcfi(pcfi){var etapa=etapaPcfi(pcfi);if(!podeEtapa(state.pedido,etapa)){toast('Você não está configurado para realizar a etapa de '+(etapa==='QUAL'?'qualidade':'análise fiscal')+'.',true);return}state.pcfi=pcfi;state.etapa=etapa;var base=state.itensAll.filter(function(r){return String(r.NUNOTA)===String(state.pedido.NUNOTA)}),salvos=state.itensPcfi.filter(function(r){return String(r.NUPCFI)===String(pcfi.NUPCFI)});state.itens=prepararItens(base,salvos);mostrarConferencia();renderItens()}
  function mostrarConferencia(){var etapa=state.etapa,nova=etapa==='QTDE';$('viewPcfis').hidden=true;$('viewPcfis').classList.add('hidden');$('viewConferencia').hidden=false;$('viewConferencia').classList.remove('hidden');$('pageTitle').textContent=(etapa==='QUAL'?'Qualidade':etapa==='FISC'?'Fiscal':'Quantidade')+' da '+(state.pcfi?'PCFI #'+state.pcfi.NUPCFI:'nova PCFI');$('pageSubtitle').textContent='Dados mantidos em memória até a confirmação do salvamento.';$('qualBadge').textContent=etapa==='QUAL'?'Qualidade':etapa==='FISC'?'Fiscal':'Quantidade';$('tituloConferencia').textContent=nova?'Identificação do recebimento':'Dados da PCFI';$('subtituloConferencia').textContent=nova?'O número da nota fiscal é obrigatório.':'Dados registrados na etapa de quantidade.';$('numNotaNf').value=nova?'':state.pcfi.NUMNOTANF;$('obsGeral').value=nova?'':state.pcfi.OBSERVACAO||'';$('numNotaNf').readOnly=!nova;$('obsGeral').readOnly=!nova;$('dadosRecebimento').classList.toggle('hidden',etapa==='FISC');$('btnSalvar').textContent=etapa==='FISC'?'Confirmar análise fiscal':etapa==='QUAL'?'Salvar qualidade':'Salvar conferência';contexto('ocContext')}
  function voltar(){if(state.cameraStream||!$('modalCamera').hidden)fecharCamera();state.pedido=null;state.pcfi=null;state.etapa='';state.itens=[];['viewConferencia','viewPcfis'].forEach(function(id){$(id).hidden=true;$(id).classList.add('hidden')});$('viewLista').hidden=false;$('viewLista').classList.remove('hidden');$('btnVoltar').hidden=true;$('btnVoltar').classList.add('hidden');$('btnAtualizar').classList.remove('hidden');$('pageTitle').textContent='Pedidos de Compra Pendentes';$('pageSubtitle').textContent='Selecione um pedido para iniciar a conferência.'}
  function token(v){return String(v==null?'':v).replace(/[^a-zA-Z0-9_-]/g,'_')}
  function field(label,type,value,attrs,id,name,content){var fieldId=id||'pcfi-field-'+token(label),fieldName=name||fieldId,common=' id="'+esc(fieldId)+'" name="'+esc(fieldName)+'" autocomplete="off" ',inputmode=type==='number'?' inputmode="decimal"':type==='text'?' inputmode="text"':type==='date'?' inputmode="numeric"':'';var control=type==='select'?'<select'+common+inputmode+(attrs||'')+'>'+(content||'')+'</select>':type==='textarea'?'<textarea'+common+inputmode+(attrs||'')+'>'+esc(value)+'</textarea>':'<input type="'+type+'" value="'+esc(value)+'"'+common+inputmode+(attrs||'')+'>';return '<label class="field" for="'+esc(fieldId)+'"><span>'+label+'</span>'+control+'</label>'}
  function checkField(label,checked,attrs,id,name){var fieldId=id||'pcfi-check-'+token(label),fieldName=name||fieldId;return '<label class="checkline" for="'+esc(fieldId)+'"><input id="'+esc(fieldId)+'" name="'+esc(fieldName)+'" type="checkbox" autocomplete="off" '+(attrs||'')+(checked?' checked':'')+'><span>'+label+'</span></label>'}
  function option(value,label,selected){return '<option value="'+esc(value)+'"'+(String(value)===String(selected)?' selected':'')+'>'+esc(label)+'</option>'}
  function fotoMarkup(it){var preview=it.fotoPreview?'<img class="photo-capture-preview" src="'+esc(it.fotoPreview)+'" alt="Prévia da foto do item">':'';var info=it.foto?'<div class="photo-capture-info"><strong>Foto capturada</strong><span>'+Math.ceil(it.foto.size/1024)+' KB</span></div><button class="icon-btn remover-foto" type="button">Remover foto</button>':'<div class="photo-capture-info"><strong>Foto do item</strong><span>Capture uma foto usando a câmera do dispositivo.</span></div>';return '<div class="photo-capture">'+preview+info+'<button class="btn btn-secondary abrir-camera" type="button">'+(it.foto?'Capturar novamente':'Abrir câmera')+'</button></div>'}
  function renderItens(){
    var quality=state.etapa==='QUAL',readonly=state.etapa!=='QTDE';
    $('itensContainer').innerHTML=state.itens.map(function(it,i){return '<article class="item-card" data-item="'+i+'"><div class="item-head"><div><h3>'+esc(it.SEQUENCIA)+' · '+esc(it.CODPROD)+' — '+esc(it.DESCRPROD)+'</h3><p>Pedido: '+fmt(it.QTDNEG)+' '+esc(it.CODVOL)+' · Pendente: '+fmt(it.QTDPENDENTE)+' '+esc(it.CODVOL)+'</p></div></div><div class="item-grid">'+
      field('Quantidade recebida *','number',it.QTDRECEBIDA,'class="bind" data-k="QTDRECEBIDA" min="0" max="'+esc(it.QTDPENDENTE)+'" step="0.0001" '+(readonly?'readonly disabled title="A quantidade recebida só pode ser alterada na etapa de quantidade."':'') ,'pcfi-'+token(it.SEQUENCIA)+'-qtd-recebida','itens['+token(it.SEQUENCIA)+'][qtdRecebida]')+(!readonly?fotoMarkup(it):'')+
      (quality?'<div class="quality-grid">'+field('Embalagem *','select',it.EMBALAGEM,'class="bind" data-k="EMBALAGEM" required', 'pcfi-'+token(it.SEQUENCIA)+'-embalagem','itens['+token(it.SEQUENCIA)+'][embalagem]',option('I','Íntegra',it.EMBALAGEM)+option('A','Avariada',it.EMBALAGEM))+field('Divergência *','select',it.DIVERGENCIA,'class="bind" data-k="DIVERGENCIA" required','pcfi-'+token(it.SEQUENCIA)+'-divergencia','itens['+token(it.SEQUENCIA)+'][divergencia]',option('N','Nenhuma',it.DIVERGENCIA)+option('E','Especificação',it.DIVERGENCIA)+option('Q','Quantidade',it.DIVERGENCIA)+option('A','Ambas',it.DIVERGENCIA))+checkField('Item impróprio',it.IMPROPRIO==='S','class="bind-check" data-k="IMPROPRIO"','pcfi-'+token(it.SEQUENCIA)+'-improprio','itens['+token(it.SEQUENCIA)+'][improprio]')+field('Qtd. imprópria *','number',it.QTDIMPROPRIA,'class="bind improper" data-k="QTDIMPROPRIA" min="0" step="0.0001" '+(it.IMPROPRIO==='S'?'required':'')+'','pcfi-'+token(it.SEQUENCIA)+'-qtd-impropria','itens['+token(it.SEQUENCIA)+'][qtdImpropria]')+checkField('Matéria-prima',it.MATERIAPRIMA==='S','class="bind-check" data-k="MATERIAPRIMA"','pcfi-'+token(it.SEQUENCIA)+'-materia-prima','itens['+token(it.SEQUENCIA)+'][materiaPrima]')+checkField('Patrimônio',it.BEM==='S','class="bind-check" data-k="BEM"','pcfi-'+token(it.SEQUENCIA)+'-bem','itens['+token(it.SEQUENCIA)+'][bem]')+field('Observação do item','textarea',it.OBSERVACAOPCFI,'class="bind" data-k="OBSERVACAOPCFI" rows="2" maxlength="4000"','pcfi-'+token(it.SEQUENCIA)+'-observacao','itens['+token(it.SEQUENCIA)+'][observacao]')+'</div><div class="conditional lotes '+(it.MATERIAPRIMA==='S'?'':'hidden')+'"><div class="conditional-head"><div><strong>Lotes da matéria-prima</strong><p>Número, quantidade, fabricação e validade são obrigatórios.</p></div><button type="button" class="btn btn-secondary add-lote">Adicionar lote</button></div><div class="subrows lotes-rows"></div></div><div class="conditional pats '+(it.BEM==='S'?'':'hidden')+'"><div class="conditional-head"><div><strong>Patrimônios</strong><p>Informe um patrimônio por unidade recebida.</p></div><button type="button" class="btn btn-secondary add-pat">Adicionar patrimônio</button></div><div class="subrows pat-rows"></div></div>':'')+
      '</div></article>'}).join('');bindItens();state.itens.forEach(function(_,i){renderSubs(i)})
  }
  function bindItens(){Array.prototype.forEach.call(document.querySelectorAll('.item-card'),function(card){var i=Number(card.dataset.item);Array.prototype.forEach.call(card.querySelectorAll('.bind'),function(el){el.oninput=function(){state.itens[i][el.dataset.k]=el.value}});Array.prototype.forEach.call(card.querySelectorAll('.bind-check'),function(el){el.checked=state.itens[i][el.dataset.k]==='S';el.onchange=function(){if((el.dataset.k==='MATERIAPRIMA'||el.dataset.k==='BEM')&&el.checked&&n(state.itens[i].QTDRECEBIDA)<=0){el.checked=false;toast('Item '+state.itens[i].SEQUENCIA+': informe quantidade recebida antes de adicionar lote ou patrimônio.',true);return}state.itens[i][el.dataset.k]=el.checked?'S':'N';if(el.dataset.k==='IMPROPRIO')card.querySelector('.improper').classList.toggle('hidden',!el.checked);if(el.dataset.k==='MATERIAPRIMA'){card.querySelector('.lotes').classList.toggle('hidden',!el.checked);if(el.checked&&!state.itens[i].lotes.length)state.itens[i].lotes.push({NROLOTE:'',QUANTIDADE:state.itens[i].QTDRECEBIDA,DTFABRICACAO:'',DTVALIDADE:''});renderSubs(i)}if(el.dataset.k==='BEM'){card.querySelector('.pats').classList.toggle('hidden',!el.checked);if(el.checked&&!state.itens[i].patrimonios.length)state.itens[i].patrimonios.push({NROPATRIMONIO:''});renderSubs(i)}}});var abrirCamera=card.querySelector('.abrir-camera'),remover=card.querySelector('.remover-foto');if(abrirCamera)abrirCamera.onclick=function(){abrirCameraItem(i)};if(remover)remover.onclick=function(){if(state.itens[i].fotoPreview)URL.revokeObjectURL(state.itens[i].fotoPreview);state.itens[i].foto=null;state.itens[i].fotoPreview='';renderItens()};var al=card.querySelector('.add-lote'),ap=card.querySelector('.add-pat');if(al)al.onclick=function(){state.itens[i].lotes.push({NROLOTE:'',QUANTIDADE:'',DTFABRICACAO:'',DTVALIDADE:''});renderSubs(i)};if(ap)ap.onclick=function(){state.itens[i].patrimonios.push({NROPATRIMONIO:''});renderSubs(i)}})}
  function renderSubs(i){var card=document.querySelector('.item-card[data-item="'+i+'"]'),it=state.itens[i];if(!card)return;var itemToken=token(it.SEQUENCIA),lr=card.querySelector('.lotes-rows'),pr=card.querySelector('.pat-rows');if(lr){lr.innerHTML=it.lotes.map(function(l,j){return '<div class="subrow" data-j="'+j+'">'+field('Número do lote *','text',l.NROLOTE,'data-lk="NROLOTE" maxlength="60" required')+field('Quantidade *','number',l.QUANTIDADE,'data-lk="QUANTIDADE" min="0" step="0.0001" required')+field('Fabricação *','date',l.DTFABRICACAO,'data-lk="DTFABRICACAO" required')+field('Validade *','date',l.DTVALIDADE,'data-lk="DTVALIDADE" required')+'<button type="button" class="icon-btn" aria-label="Remover lote '+(j+1)+' do item '+esc(it.SEQUENCIA)+'">Remover</button></div>'}).join('');Array.prototype.forEach.call(lr.querySelectorAll('.subrow'),function(row){var j=Number(row.dataset.j);Array.prototype.forEach.call(row.querySelectorAll('[data-lk]'),function(el){var id='pcfi-'+itemToken+'-lote-'+j+'-'+el.dataset.lk.toLowerCase();el.id=id;el.name='itens['+itemToken+'][lotes]['+j+']['+el.dataset.lk.toLowerCase()+']';var label=el.closest('.field');if(label)label.htmlFor=id;el.oninput=function(){it.lotes[j][el.dataset.lk]=el.value}});row.querySelector('.icon-btn').onclick=function(){it.lotes.splice(j,1);renderSubs(i)}})}if(pr){pr.innerHTML=it.patrimonios.map(function(p,j){return '<div class="subrow pat-row" data-j="'+j+'">'+field('Número do patrimônio *','text',p.NROPATRIMONIO,'data-pk="NROPATRIMONIO" maxlength="60" required')+'<button type="button" class="icon-btn" aria-label="Remover patrimônio '+(j+1)+' do item '+esc(it.SEQUENCIA)+'">Remover</button></div>'}).join('');Array.prototype.forEach.call(pr.querySelectorAll('.pat-row'),function(row){var j=Number(row.dataset.j),el=row.querySelector('[data-pk]'),id='pcfi-'+itemToken+'-patrimonio-'+j+'-numero';el.id=id;el.name='itens['+itemToken+'][patrimonios]['+j+'][numero]';var label=el.closest('.field');if(label)label.htmlFor=id;el.oninput=function(){it.patrimonios[j].NROPATRIMONIO=el.value};row.querySelector('.icon-btn').onclick=function(){it.patrimonios.splice(j,1);renderSubs(i)}})}}
  function renderItens(){
    var quality=state.etapa==='QUAL',readonly=state.etapa!=='QTDE';
    $('itensContainer').innerHTML=state.itens.map(function(it,i){
      var itemToken=token(it.SEQUENCIA),qualityId='pcfi-'+itemToken+'-qualidade';
      var quantity='<fieldset class="item-section item-quantity"><legend>Quantidade e recebimento</legend>'+field('Quantidade recebida *','number',it.QTDRECEBIDA,'class="bind" data-k="QTDRECEBIDA" min="0" max="'+esc(it.QTDPENDENTE)+'" step="0.0001" '+(readonly?'readonly disabled title="A quantidade recebida só pode ser alterada na etapa de quantidade."':'') ,'pcfi-'+itemToken+'-qtd-recebida','itens['+itemToken+'][qtdRecebida]')+(!readonly?fotoMarkup(it):'')+'</fieldset>';
      var qualityMarkup=quality?'<fieldset id="'+qualityId+'" class="quality-grid item-section"><legend>Qualidade do item</legend>'+field('Embalagem *','select',it.EMBALAGEM,'class="bind" data-k="EMBALAGEM" required','pcfi-'+itemToken+'-embalagem','itens['+itemToken+'][embalagem]',option('I','Íntegra',it.EMBALAGEM)+option('A','Avariada',it.EMBALAGEM))+field('Divergência *','select',it.DIVERGENCIA,'class="bind" data-k="DIVERGENCIA" required','pcfi-'+itemToken+'-divergencia','itens['+itemToken+'][divergencia]',option('N','Nenhuma',it.DIVERGENCIA)+option('E','Especificação',it.DIVERGENCIA)+option('Q','Quantidade',it.DIVERGENCIA)+option('A','Ambas',it.DIVERGENCIA))+checkField('Item impróprio',it.IMPROPRIO==='S','class="bind-check" data-k="IMPROPRIO"','pcfi-'+itemToken+'-improprio','itens['+itemToken+'][improprio]')+field('Qtd. imprópria *','number',it.QTDIMPROPRIA,'class="bind improper '+(it.IMPROPRIO==='S'?'':'hidden')+'" data-k="QTDIMPROPRIA" min="0" step="0.0001" '+(it.IMPROPRIO==='S'?'required':'') ,'pcfi-'+itemToken+'-qtd-impropria','itens['+itemToken+'][qtdImpropria]')+checkField('Matéria-prima',it.MATERIAPRIMA==='S','class="bind-check" data-k="MATERIAPRIMA"','pcfi-'+itemToken+'-materia-prima','itens['+itemToken+'][materiaPrima]')+checkField('Patrimônio',it.BEM==='S','class="bind-check" data-k="BEM"','pcfi-'+itemToken+'-bem','itens['+itemToken+'][bem]')+'<details class="conditional item-observacao" '+(it.OBSERVACAOPCFI?'open':'')+'><summary>Observações do item</summary>'+field('Observação do item','textarea',it.OBSERVACAOPCFI,'class="bind" data-k="OBSERVACAOPCFI" rows="2" maxlength="4000"','pcfi-'+itemToken+'-observacao','itens['+itemToken+'][observacao]')+'</details></fieldset>':'';
      var lotes='<details class="conditional lotes '+(it.MATERIAPRIMA==='S'?'':'hidden')+'" '+(it.MATERIAPRIMA==='S'?'open':'')+'><summary>Lotes da matéria-prima</summary><div class="conditional-head"><p>Número, quantidade, fabricação e validade são obrigatórios.</p><button type="button" class="btn btn-secondary add-lote">Adicionar lote</button></div><div class="subrows lotes-rows"></div></details>';
      var patrimonios='<details class="conditional pats '+(it.BEM==='S'?'':'hidden')+'" '+(it.BEM==='S'?'open':'')+'><summary>Patrimônios</summary><div class="conditional-head"><p>Informe um patrimônio por unidade recebida.</p><button type="button" class="btn btn-secondary add-pat">Adicionar patrimônio</button></div><div class="subrows pat-rows"></div></details>';
      return '<article class="item-card" data-item="'+i+'"><div class="item-head"><div><span class="item-kicker">Item '+esc(it.SEQUENCIA)+'</span><h3>'+esc(it.CODPROD)+' — '+esc(it.DESCRPROD)+'</h3><p>Pedido: '+fmt(it.QTDNEG)+' '+esc(it.CODVOL)+' · Pendente: '+fmt(it.QTDPENDENTE)+' '+esc(it.CODVOL)+'</p></div></div><div class="item-grid">'+quantity+qualityMarkup+lotes+patrimonios+'</div></article>'
    }).join('');
    bindItens();
    state.itens.forEach(function(_,i){renderSubs(i)})
  }
  function fecharCamera(restaurar){if(state.cameraStream)state.cameraStream.getTracks().forEach(function(track){track.stop()});state.cameraStream=null;state.cameraItem=-1;$('cameraPreview').srcObject=null;$('modalCamera').hidden=true;$('modalCamera').classList.add('hidden');fecharModalAcessivel(restaurar!==false);state.cameraOpener=null}
  async function abrirCameraItem(i){var retorno=document.activeElement;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){toast('A câmera não é suportada neste navegador.',true);return}try{state.cameraOpener=retorno;state.cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});state.cameraItem=i;$('cameraPreview').srcObject=state.cameraStream;$('modalCamera').hidden=false;$('modalCamera').classList.remove('hidden');abrirModalAcessivel($('modalCamera'),retorno,$('btnCapturarFoto'),function(){fecharCamera()})}catch(e){state.cameraStream=null;state.cameraOpener=null;toast('Não foi possível abrir a câmera. Verifique a permissão do navegador.',true)}}
  function capturarFoto(){var video=$('cameraPreview'),i=state.cameraItem;if(i<0||!video.videoWidth){toast('A câmera ainda não está pronta.',true);return}var canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(function(blob){if(!blob){toast('Não foi possível capturar a foto.',true);return}if(state.itens[i].fotoPreview)URL.revokeObjectURL(state.itens[i].fotoPreview);state.itens[i].foto=new File([blob],'pcfi-item-'+state.itens[i].SEQUENCIA+'.jpg',{type:'image/jpeg'});state.itens[i].fotoPreview=URL.createObjectURL(blob);fecharCamera(false);renderItens();var botao=document.querySelector('.item-card[data-item="'+i+'"] .abrir-camera');if(botao)botao.focus()},'image/jpeg',.88)}
  function validar(){
     var errors=[];if(!$('numNotaNf').value.trim())errors.push('Informe o número da nota fiscal.');var ativos=state.itens.filter(function(it){return n(it.QTDRECEBIDA)>0});if(!ativos.length)errors.push('Informe quantidade recebida em ao menos um item.');var quality=state.etapa==='QUAL';if(quality)state.itens.forEach(function(it){if(n(it.QTDRECEBIDA)<=0&&(it.MATERIAPRIMA==='S'||it.BEM==='S'))errors.push('Item '+it.SEQUENCIA+': lote e patrimônio exigem quantidade recebida.');});
    ativos.forEach(function(it){if(state.etapa==='QTDE'&&n(it.QTDRECEBIDA)>n(it.QTDPENDENTE))errors.push('Item '+it.SEQUENCIA+': quantidade recebida maior que a pendente.');if(!quality)return;if(it.IMPROPRIO==='S'&&(n(it.QTDIMPROPRIA)<=0||n(it.QTDIMPROPRIA)>n(it.QTDRECEBIDA)))errors.push('Item '+it.SEQUENCIA+': quantidade imprópria inválida.');if(it.MATERIAPRIMA==='S'){if(!it.lotes.length)errors.push('Item '+it.SEQUENCIA+': adicione ao menos um lote.');var soma=0;it.lotes.forEach(function(l){soma+=n(l.QUANTIDADE);if(!l.NROLOTE.trim()||n(l.QUANTIDADE)<=0||!l.DTFABRICACAO||!l.DTVALIDADE)errors.push('Item '+it.SEQUENCIA+': preencha todos os campos dos lotes.');if(l.DTFABRICACAO&&l.DTVALIDADE&&l.DTVALIDADE<l.DTFABRICACAO)errors.push('Item '+it.SEQUENCIA+': validade anterior à fabricação.');});if(Math.abs(soma-n(it.QTDRECEBIDA))>.0001)errors.push('Item '+it.SEQUENCIA+': soma dos lotes difere da quantidade recebida.')}if(it.BEM==='S'){if(it.patrimonios.length!==n(it.QTDRECEBIDA))errors.push('Item '+it.SEQUENCIA+': patrimônios devem corresponder à quantidade recebida.');it.patrimonios.forEach(function(p){if(!p.NROPATRIMONIO.trim())errors.push('Item '+it.SEQUENCIA+': informe todos os patrimônios.')})}});return {errors:errors,ativos:ativos}
  }
  function fecharModalFiscal(){$('modalFiscal').hidden=true;$('modalFiscal').classList.add('hidden');fecharModalAcessivel(true)}
  function abrirModalFiscal(){var modal=$('modalFiscal'),retorno=document.activeElement;modal.hidden=false;modal.classList.remove('hidden');abrirModalAcessivel(modal,retorno,$('btnFiscalAprovar'),function(){fecharModalFiscal()})}
  function fecharModalQualidade(){$('modalQualidade').hidden=true;$('modalQualidade').classList.add('hidden');fecharModalAcessivel(true)}
  function abrirModalQualidade(){var modal=$('modalQualidade'),retorno=document.activeElement;modal.hidden=false;modal.classList.remove('hidden');abrirModalAcessivel(modal,retorno,$('btnQualidadeAprovar'),function(){fecharModalQualidade()})}
  // O AnexoSistema acrescenta automaticamente o sufixo da entidade ao PKREGISTRO.
  // Enviar o nome da entidade aqui duplicaria o sufixo (ex.: ..._AD_PCFIITE_AD_PCFIITE).
  function pkRegistroItem(nupcfi,sequencia){return String(nupcfi)+'_'+String(sequencia)}
  async function anexarFotoItem(nupcfi,sequencia,arquivo){var pk=pkRegistroItem(nupcfi,sequencia),sessao='ANEXO_SISTEMA_AD_PCFIITE_'+pk,form=new FormData();form.append('arquivo',arquivo,arquivo.name||'foto-pcfi.jpg');var upload=await fetch(window.location.origin+'/mge/sessionUpload.mge?sessionkey='+encodeURIComponent(sessao)+'&fitem=S&salvar=S&useCache=N',{method:'POST',credentials:'same-origin',body:form});if(!upload.ok)throw new Error('Não foi possível enviar a foto do item.');var body={serviceName:'AnexoSistemaSP.salvar',requestBody:{params:{pkEntity:pk,keySession:sessao,nameEntity:'AD_PCFIITE',description:'Foto PCFI',keyAttach:'',typeAcess:'ALL',typeApres:'GLO',nuAttach:'',nameAttach:arquivo.name||'foto-pcfi.jpg',fileSelect:1,oldFile:''}}};var resp=await post(window.location.origin+'/mge/service.sbr?serviceName=AnexoSistemaSP.salvar&outputType=json',body);if(String(resp.status)!=='1')throw new Error(resp.statusMessage||'Não foi possível vincular a foto ao item.')}
  async function decidirFiscal(aprovada){fecharModalFiscal();loading(true,'Salvando análise fiscal...');$('btnSalvar').disabled=true;try{await apiSave({STATUSPCFI:'C',STATUSFISCAL:aprovada?'A':'N',RESULTADOPCFI:aprovada?'A':'N',CODUSUFISC:cfg.codUsu,DHCONCFISC:new Date().toISOString()},'AD_PCFI',{NUPCFI:state.pcfi.NUPCFI});toast('Análise fiscal '+(aprovada?'aprovada':'negada')+'.');window.setTimeout(function(){window.location.reload()},900)}catch(e){toast('Falha na análise fiscal: '+(e.message||e),true)}finally{loading(false);$('btnSalvar').disabled=false}}
  async function salvar(resultadoQualidade){
    if(!cfg.codUsu){toast('Código do usuário logado não foi disponibilizado pelo gadget.',true);return}
    if(state.etapa==='FISC'){abrirModalFiscal();return}
    var v=validar();if(v.errors.length){toast(v.errors[0]+(v.errors.length>1?' (e mais '+(v.errors.length-1)+' pendência(s))':''),true);return}if(state.etapa==='QUAL'&&!resultadoQualidade){abrirModalQualidade();return}if(state.etapa==='QTDE'&&!await confirmar('Salvar conferência de quantidade','Confirma o salvamento definitivo desta conferência de quantidade?','Salvar definitivamente'))return;loading(true,'Salvando PCFI...');$('btnSalvar').disabled=true;
    try{
      var nupcfi=state.pcfi&&state.pcfi.NUPCFI,parcial=v.ativos.length<state.itens.length||v.ativos.some(function(it){return n(it.QTDRECEBIDA)<n(it.QTDPENDENTE)}),q=state.etapa==='QUAL';
      if(!nupcfi){if(state.pcfis.some(function(p){return String(p.NUNOTAOC)===String(state.pedido.NUNOTA)&&String(p.NUMNOTANF)===String($('numNotaNf').value.trim())}))throw new Error('Já existe uma PCFI para esta nota fiscal e OC.');var h=await apiSave({CODEMP:state.pedido.CODEMP,NUNOTAOC:state.pedido.NUNOTA,NUMNOTANF:$('numNotaNf').value.trim(),CODPARC:state.pedido.CODPARC,CODCENCUS:state.pedido.CODCENCUS,STATUSPCFI:'Q',STATUSQUAL:'P',STATUSFISCAL:'P',RESULTADOPCFI:'P',PRIORIDADE:'N',ENTREGAPARCIAL:parcial?'S':'N',OBSERVACAO:$('obsGeral').value.trim(),CODUSUINC:cfg.codUsu,CODUSUQTDE:cfg.codUsu,DHCONCQTDE:new Date().toISOString()},'AD_PCFI',null,['NUPCFI']);nupcfi=h.NUPCFI;if(!nupcfi)throw new Error('A inclusão de AD_PCFI não retornou NUPCFI.');for(var x=0;x<v.ativos.length;x++){var it=v.ativos[x],ir=await apiSave({NUPCFI:nupcfi,NUNOTAOC:it.NUNOTA,SEQITEMOC:it.SEQUENCIA,CODPROD:it.CODPROD,QTDRECEBIDA:n(it.QTDRECEBIDA),IMPROPRIO:'N',QTDIMPROPRIA:0,DIVERGENCIA:'N',EMBALAGEM:'I',MATERIAPRIMA:'N',BEM:'N',OBSERVACAO:''},'AD_PCFIITE',null,['SEQUENCIA']);if(!ir.SEQUENCIA)throw new Error('O item '+it.SEQUENCIA+' não retornou SEQUENCIA.');it.SEQPCFIITEM=ir.SEQUENCIA;if(it.foto)await anexarFotoItem(nupcfi,ir.SEQUENCIA,it.foto)}}
      else if(q){await apiSave({STATUSPCFI:resultadoQualidade==='N'?'N':'F',STATUSQUAL:resultadoQualidade,STATUSFISCAL:resultadoQualidade==='N'?'C':'P',CODUSUQUAL:cfg.codUsu,DHCONCQUAL:new Date().toISOString()},'AD_PCFI',{NUPCFI:nupcfi});for(var y=0;y<v.ativos.length;y++){var qi=v.ativos[y];await apiSave({IMPROPRIO:qi.IMPROPRIO,QTDIMPROPRIA:qi.IMPROPRIO==='S'?n(qi.QTDIMPROPRIA):0,DIVERGENCIA:qi.DIVERGENCIA,EMBALAGEM:qi.EMBALAGEM,MATERIAPRIMA:qi.MATERIAPRIMA,BEM:qi.BEM,OBSERVACAO:qi.OBSERVACAOPCFI},'AD_PCFIITE',{NUPCFI:nupcfi,SEQUENCIA:qi.SEQPCFIITEM})}}
      toast('PCFI '+nupcfi+' salva com sucesso.');window.setTimeout(function(){window.location.reload()},900);
    }catch(e){toast('Falha no salvamento: '+(e.message||e)+'. Consulte o PCFI antes de tentar novamente.',true)}finally{loading(false);$('btnSalvar').disabled=false}
  }
  $('btnAtualizar').onclick=carregarPedidos;$('btnVoltar').onclick=voltar;$('btnVoltarPcfis').onclick=voltar;$('btnCancelar').onclick=function(){abrirPedido(state.pedido)};$('btnSalvar').onclick=function(){salvar()};$('btnFiscalAprovar').onclick=function(){decidirFiscal(true)};$('btnFiscalNegar').onclick=function(){decidirFiscal(false)};$('btnFiscalCancelar').onclick=fecharModalFiscal;$('btnQualidadeAprovar').onclick=function(){fecharModalQualidade();salvar('A')};$('btnQualidadeRessalva').onclick=function(){fecharModalQualidade();salvar('R')};$('btnQualidadeNegar').onclick=function(){fecharModalQualidade();salvar('N')};$('btnQualidadeCancelar').onclick=fecharModalQualidade;$('btnCapturarFoto').onclick=capturarFoto;$('btnCancelarCamera').onclick=fecharCamera;$('btnPaginaAnterior').onclick=function(){if(state.paginaPedidos>1){state.paginaPedidos--;renderPedidos(state.pedidosFiltrados)}};$('btnProximaPagina').onclick=function(){var totalPaginas=Math.ceil(state.pedidosFiltrados.length/state.pedidosPorPagina);if(state.paginaPedidos<totalPaginas){state.paginaPedidos++;renderPedidos(state.pedidosFiltrados)}};$('buscaPedidos').oninput=function(){var q=this.value.toLowerCase();state.paginaPedidos=1;state.pedidosFiltrados=state.pedidos.filter(function(r){return [r.NUNOTA,r.NUMNOTA,r.CODPARC,r.NOMEPARC,r.CODCENCUS].join(' ').toLowerCase().indexOf(q)>=0});renderPedidos(state.pedidosFiltrados)};carregarPedidos();
  function limparErros(){
    Array.prototype.forEach.call(document.querySelectorAll('.field-error'),function(el){if(el.parentNode)el.parentNode.removeChild(el)});
    Array.prototype.forEach.call(document.querySelectorAll('[aria-invalid="true"]'),function(el){el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby')})
  }
  function criarErro(message,selector){return {message:message,selector:selector,toString:function(){return this.message}}}
  function fieldSelector(i,key){return '.item-card[data-item="'+i+'"] [data-k="'+key+'"]'}
  function loteSelector(i,j,key){return '.item-card[data-item="'+i+'"] .lotes-rows .subrow[data-j="'+j+'"] [data-lk="'+key+'"]'}
  function patrimonioSelector(i,j){return '.item-card[data-item="'+i+'"] .pat-rows .subrow[data-j="'+j+'"] [data-pk="NROPATRIMONIO"]'}
  function apresentarErros(errors){
    var primeiro=null,descricoes={};
    errors.forEach(function(error,index){
      var target=document.querySelector(error.selector);if(!target)return;
      if(!target.id)target.id='pcfi-error-target-'+index;
      target.setAttribute('aria-invalid','true');
      var details=target.closest('details');if(details)details.open=true;
      var descId=target.id+'-error-'+index,desc=document.createElement('span');desc.id=descId;desc.className='field-error';desc.setAttribute('role','alert');desc.textContent=error.message;
      var holder=target.closest('.field')||target.closest('.checkline')||target.parentNode;if(holder)holder.appendChild(desc);
      descricoes[target.id]=(descricoes[target.id]||[]).concat(descId);if(!primeiro)primeiro=target
    });
    Object.keys(descricoes).forEach(function(id){var target=document.getElementById(id);if(target)target.setAttribute('aria-describedby',descricoes[id].join(' '))});
    if(primeiro&&primeiro.focus)primeiro.focus()
  }
  function validarContextual(){
    limparErros();
    var errors=[],add=function(message,selector){errors.push(criarErro(message,selector))},ativos=state.itens.filter(function(it){return n(it.QTDRECEBIDA)>0}),quality=state.etapa==='QUAL';
    if(!$('numNotaNf').value.trim())add('Cabeçalho — número da nota fiscal: informe o número para continuar.','#numNotaNf');
    if(!ativos.length)add('Itens — quantidade recebida: informe uma quantidade maior que zero em pelo menos um item.',state.itens.length?fieldSelector(0,'QTDRECEBIDA'):'#numNotaNf');
    state.itens.forEach(function(it,i){if(quality&&n(it.QTDRECEBIDA)<=0&&(it.MATERIAPRIMA==='S'||it.BEM==='S'))add('Item '+it.SEQUENCIA+' — quantidade recebida: informe uma quantidade antes de adicionar lote ou patrimônio.',fieldSelector(i,'QTDRECEBIDA'))});
    ativos.forEach(function(it){
      var i=state.itens.indexOf(it);
      if(state.etapa==='QTDE'&&n(it.QTDRECEBIDA)>n(it.QTDPENDENTE))add('Item '+it.SEQUENCIA+' — quantidade recebida: reduza o valor para no máximo '+fmt(it.QTDPENDENTE)+'.',fieldSelector(i,'QTDRECEBIDA'));
      if(!quality)return;
      if(it.IMPROPRIO==='S'&&n(it.QTDIMPROPRIA)<=0)add('Item '+it.SEQUENCIA+' — quantidade imprópria: informe um valor maior que zero.',fieldSelector(i,'QTDIMPROPRIA'));
      if(it.IMPROPRIO==='S'&&n(it.QTDIMPROPRIA)>n(it.QTDRECEBIDA))add('Item '+it.SEQUENCIA+' — quantidade imprópria: informe um valor até a quantidade recebida.',fieldSelector(i,'QTDIMPROPRIA'));
      if(it.MATERIAPRIMA==='S'){
        if(!it.lotes.length)add('Item '+it.SEQUENCIA+' — lotes: adicione ao menos um lote.', '.item-card[data-item="'+i+'"] .add-lote');
        var soma=0;it.lotes.forEach(function(l,j){soma+=n(l.QUANTIDADE);if(!String(l.NROLOTE||'').trim())add('Item '+it.SEQUENCIA+' — número do lote: informe o número do lote.',loteSelector(i,j,'NROLOTE'));if(n(l.QUANTIDADE)<=0)add('Item '+it.SEQUENCIA+' — quantidade do lote: informe um valor maior que zero.',loteSelector(i,j,'QUANTIDADE'));if(!l.DTFABRICACAO)add('Item '+it.SEQUENCIA+' — fabricação do lote: informe a data de fabricação.',loteSelector(i,j,'DTFABRICACAO'));if(!l.DTVALIDADE)add('Item '+it.SEQUENCIA+' — validade do lote: informe a data de validade.',loteSelector(i,j,'DTVALIDADE'));if(l.DTFABRICACAO&&l.DTVALIDADE&&l.DTVALIDADE<l.DTFABRICACAO)add('Item '+it.SEQUENCIA+' — validade do lote: informe uma data posterior à fabricação.',loteSelector(i,j,'DTVALIDADE'))});
        if(Math.abs(soma-n(it.QTDRECEBIDA))>.0001)add('Item '+it.SEQUENCIA+' — lotes: ajuste a soma dos lotes para igualar a quantidade recebida.', '.item-card[data-item="'+i+'"] .lotes-rows [data-lk="QUANTIDADE"]')
      }
      if(it.BEM==='S'){
        if(it.patrimonios.length!==n(it.QTDRECEBIDA))add('Item '+it.SEQUENCIA+' — patrimônios: informe um patrimônio por unidade recebida.',it.patrimonios.length?patrimonioSelector(i,0):'.item-card[data-item="'+i+'"] .add-pat');
        it.patrimonios.forEach(function(p,j){if(!String(p.NROPATRIMONIO||'').trim())add('Item '+it.SEQUENCIA+' — número do patrimônio: informe o número do patrimônio.',patrimonioSelector(i,j))})
      }
    });
    apresentarErros(errors);return {errors:errors,ativos:ativos}
  }
  function confirmarSaida(){return !state.alterado?Promise.resolve(true):confirmar('Descartar alterações','Existem dados preenchidos nesta conferência. Deseja sair e descartar as alterações?','Descartar alterações')}
  async function voltarSeguro(){if(!await confirmarSaida())return;state.alterado=false;voltar()}
  async function cancelarSeguro(){if(!await confirmarSaida())return;var pedido=state.pedido;state.alterado=false;abrirPedido(pedido)}
  document.addEventListener('input',function(e){var el=e.target;if(!el||!el.closest||!el.closest('#viewConferencia'))return;if(el.tagName==='INPUT'||el.tagName==='SELECT'||el.tagName==='TEXTAREA')state.alterado=true});
  document.addEventListener('change',function(e){var el=e.target;if(el&&el.closest&&el.closest('#viewConferencia'))state.alterado=true});
  document.addEventListener('click',function(e){var el=e.target;if(!el||!el.closest||!el.closest('#viewConferencia'))return;if(el.id==='btnCapturarFoto'||el.closest('.add-lote,.add-pat,.remover-foto'))state.alterado=true});
  $('btnVoltar').onclick=voltarSeguro;$('btnVoltarPcfis').onclick=voltarSeguro;$('btnCancelar').onclick=cancelarSeguro;
  validar=validarContextual;
})();
