/* Dashboard PCFI */
(function(){
  'use strict';
  var cfg=window.PCFI_CONFIG||{},state={pedidos:[],pedido:null,pcfi:null,etapa:'',pcfis:[],itens:[],itensAll:[],itensPcfi:[],paginaPedidos:1,pedidosPorPagina:20,pedidosFiltrados:[]};
  var $=function(id){return document.getElementById(id)};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function n(v){var x=Number(String(v==null?'':v).replace(',','.'));return isFinite(x)?x:0}
  function fmt(v){return n(v).toLocaleString('pt-BR',{minimumFractionDigits:0,maximumFractionDigits:4})}
  function isoDate(v){var m=String(v||'').match(/^(\d{4}-\d{2}-\d{2})/);if(m)return m[1];m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:''}
  function sqlDate(v){var d=isoDate(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(d))throw new Error('Data de filtro inválida.');return d}
  function loading(on,text){$('loading').hidden=!on;$('loading').classList.toggle('hidden',!on);$('loadingText').textContent=text||'Carregando...'}
  function toast(msg,error){var el=$('toast');el.hidden=false;el.textContent=msg;el.className='toast'+(error?' error':'');setTimeout(function(){el.hidden=true;el.classList.add('hidden')},5000)}
  function post(url,body){
    return fetch(url,{method:'POST',credentials:'same-origin',redirect:'follow',headers:{'Content-Type':'application/json;charset=UTF-8'},body:JSON.stringify(body)})
      .then(function(r){return r.json()});
  }
  function apiSave(campos,entidade,pk,returnFields){
    var localFields={},fieldNames=Object.keys(campos);
    (returnFields||[]).forEach(function(field){if(fieldNames.indexOf(field)<0)fieldNames.push(field)});
    fieldNames.forEach(function(key){var value=campos[key];if(value!==null&&value!==undefined&&value!=='')localFields[key.toUpperCase()]={$:String(value)}});
    var dataRow={localFields:localFields};
    if(pk){dataRow.key={};Object.keys(pk).forEach(function(key){dataRow.key[key.toUpperCase()]={$:String(pk[key])}})}
    var body={serviceName:'CRUDServiceProvider.saveRecord',requestBody:{dataSet:{rootEntity:entidade,includePresentationFields:'N',dataRow:dataRow,entity:{fieldset:{list:fieldNames.map(function(k){return k.toUpperCase()}).join(',')}}}}};
    var url=window.location.origin+'/mge/service.sbr?serviceName=CRUDServiceProvider.saveRecord&outputType=json';
    return post(url,body).then(function(data){
      if(String(data.status)!=='1')throw new Error(data.statusMessage||(data.responseBody&&data.responseBody.message)||('Falha ao salvar '+entidade));
      var entity=data.responseBody&&data.responseBody.entities&&data.responseBody.entities.entity;
      if(Array.isArray(entity))entity=entity[0];
      if(!entity)throw new Error('O Sankhya não devolveu a entidade gravada em '+entidade+'.');
      var result={};Object.keys(entity).forEach(function(key){result[key]=entity[key]&&entity[key].$!==undefined?entity[key].$:entity[key]});
      return result;
    });
  }
  window.saveRecords=apiSave;

  function carregarPedidos(){
    loading(true,'Lendo pedidos pendentes...');
    try{
      state.pedidos=Array.prototype.map.call(document.querySelectorAll('#data-pedidos .data-pedido'),function(el){var d=el.dataset;return {NUNOTA:d.nunota,NUMNOTA:d.numnota,DTNEG:d.dtneg,CODEMP:d.codemp,CODPARC:d.codparc,NOMEPARC:d.nomeparc,CODCENCUS:d.codcencus,DESCRCR:d.descrCr,QTD_ITENS:d.qtdItens,QTD_PENDENTE:d.qtdPendente,QTD_PCFI:d.qtdPcfi,QUALPELCONF:d.qualpelconf,CODUSULOGADO:d.codusuLogado,PODEPRIORIDADE:d.podePrioridade,PODEQTDE:d.podeQtde,PODEQUAL:d.podeQual,PODEFISC:d.podeFisc,STATUSOC:d.statusOc}});
      state.pcfis=Array.prototype.map.call(document.querySelectorAll('#data-pcfis .data-pcfi'),function(el){var d=el.dataset;return {NUPCFI:d.nupcfi,NUNOTAOC:d.nunotaoc,NUMNOTANF:d.numnotanf,STATUSPCFI:d.statuspcfi,STATUSQUAL:d.statusqual,STATUSFISCAL:d.statusfiscal,PRIORIDADE:d.prioridade,ENTREGAPARCIAL:d.entregaparcial,OBSERVACAO:d.observacao}});
      state.itensAll=Array.prototype.map.call(document.querySelectorAll('#data-itens .data-item'),function(el){var d=el.dataset;return {NUNOTA:d.nunota,SEQUENCIA:d.sequencia,CODPROD:d.codprod,DESCRPROD:d.descrprod,CODVOL:d.codvol,QTDNEG:d.qtdneg,QTDPENDENTE:d.qtdpendente,QTDENTREGUE:d.qtdentregue,OBSERVACAO:d.observacao}});
      state.itensPcfi=Array.prototype.map.call(document.querySelectorAll('#data-itens-pcfi .data-item-pcfi'),function(el){var d=el.dataset;return {NUPCFI:d.nupcfi,SEQPCFIITEM:d.seqpcfiitem,NUNOTA:d.nunota,SEQUENCIA:d.sequencia,CODPROD:d.codprod,QTDRECEBIDA:d.qtdrecebida,IMPROPRIO:d.improprio,QTDIMPROPRIA:d.qtdimpropria,DIVERGENCIA:d.divergencia,EMBALAGEM:d.embalagem,MATERIAPRIMA:d.materiaprima,BEM:d.bem,OBSERVACAOPCFI:d.observacao}});
      state.paginaPedidos=1;state.pedidosFiltrados=state.pedidos;renderPedidos(state.pedidosFiltrados);
    }catch(e){toast('Não foi possível carregar os pedidos: '+(e.message||e),true)}finally{loading(false)}
  }
  function etapaPcfi(p){if(p.STATUSPCFI==='Q')return 'QUAL';if(p.STATUSPCFI==='F')return 'FISC';return ''}
  function podeEtapa(pedido,etapa){return etapa==='QUAL'?pedido.PODEQUAL==='S':etapa==='FISC'?pedido.PODEFISC==='S':pedido.PODEQTDE==='S'}
  function classePcfi(p){if(p.PRIORIDADE==='S'&&p.STATUSPCFI!=='C')return ' pcfi-prioridade';if(p.STATUSPCFI==='F')return ' pcfi-qual';if(p.STATUSPCFI==='Q')return ' pcfi-qtde';return ''}
  function renderPedidos(rows){
    var totalPaginas=Math.max(1,Math.ceil(rows.length/state.pedidosPorPagina));if(state.paginaPedidos>totalPaginas)state.paginaPedidos=totalPaginas;
    var inicio=(state.paginaPedidos-1)*state.pedidosPorPagina,pagina=rows.slice(inicio,inicio+state.pedidosPorPagina),body=$('pedidosBody');
    body.innerHTML=pagina.map(function(r,i){return '<tr data-i="'+(inicio+i)+'"><td><strong>'+esc(r.NUMNOTA||r.NUNOTA)+'</strong><br><small>#'+esc(r.NUNOTA)+'</small></td><td>'+esc(r.DTNEG)+'</td><td>'+esc(r.CODEMP)+'</td><td><span class="fornecedor" title="'+esc(r.CODPARC)+' - '+esc(r.NOMEPARC)+'">'+esc((String(r.CODPARC)+' - '+String(r.NOMEPARC)).slice(0,40))+'</span></td><td>'+esc(r.DESCRCR)+'</td><td>'+fmt(r.QTD_PENDENTE)+'</td><td><span class="badge">'+esc(r.STATUSOC)+'</span></td><td><span class="badge">PCFIs</span></td></tr>'}).join('');
    $('listaVazia').classList.toggle('hidden',rows.length!==0);$('sumPedidos').textContent=rows.length;$('sumItens').textContent=state.itensAll.length;$('sumQtd').textContent=fmt(rows.reduce(function(a,r){return a+n(r.QTD_PENDENTE)},0));$('paginacaoPedidos').hidden=rows.length<=state.pedidosPorPagina;$('paginaPedidos').textContent='Página '+state.paginaPedidos+' de '+totalPaginas;$('btnPaginaAnterior').disabled=state.paginaPedidos===1;$('btnProximaPagina').disabled=state.paginaPedidos===totalPaginas;
    Array.prototype.forEach.call(body.querySelectorAll('tr'),function(tr){tr.ondblclick=function(){abrirPedido(rows[Number(tr.dataset.i)])}})
  }
  function contexto(id){$(id).innerHTML=[['Nro. único',state.pedido.NUNOTA],['Fornecedor',state.pedido.CODPARC+' - '+state.pedido.NOMEPARC],['Centro de resultado',state.pedido.DESCRCR]].map(function(x){return '<div><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>'}).join('')}
  function abrirPedido(pedido){state.pedido=pedido;cfg.codUsu=pedido.CODUSULOGADO;state.pcfi=null;state.etapa='';$('viewLista').hidden=true;$('viewLista').classList.add('hidden');$('viewPcfis').hidden=false;$('viewPcfis').classList.remove('hidden');$('btnVoltar').hidden=false;$('btnVoltar').classList.remove('hidden');$('btnAtualizar').classList.add('hidden');$('pageTitle').textContent='PCFIs da OC '+(pedido.NUMNOTA||pedido.NUNOTA);$('pageSubtitle').textContent='Selecione uma PCFI existente ou registre uma nova chegada.';contexto('ocContextPcfis');renderPcfis()}
  function renderPcfis(){var pcfis=state.pcfis.filter(function(p){return String(p.NUNOTAOC)===String(state.pedido.NUNOTA)}),html='';if(state.pedido.PODEQTDE==='S'&&n(state.pedido.QTD_PENDENTE)>0)html+='<div class="pcfi-row"><div><strong>Nova PCFI</strong><p>Saldo operacional: '+fmt(state.pedido.QTD_PENDENTE)+'</p></div><button class="btn btn-primary" data-nova-pcfi="S" type="button">Conferir quantidade</button></div>';pcfis.forEach(function(p,i){var etapa=etapaPcfi(p),pode=podeEtapa(state.pedido,etapa),status=p.ENTREGAPARCIAL==='S'?'PCFI Parcial · ':'';status+=etapa==='QUAL'?'Aguardando Qualidade':etapa==='FISC'?'Aguardando Fiscal':'Concluída';var prioridade=state.pedido.PODEPRIORIDADE==='S'&&p.PRIORIDADE!=='S'&&p.STATUSPCFI!=='C'?'<button class="btn btn-secondary" data-prioridade-i="'+i+'" type="button">Solicitar prioridade</button>':'';html+='<div class="pcfi-row'+classePcfi(p)+'"><div><strong>PCFI #'+esc(p.NUPCFI)+'</strong><p>NF: '+esc(p.NUMNOTANF)+' · '+status+(p.ENTREGAPARCIAL==='S'?' · Parcial':'')+'</p></div>'+(etapa&&pode?'<button class="btn btn-secondary" data-pcfi-i="'+i+'" type="button">Abrir '+(etapa==='QUAL'?'qualidade':'fiscal')+'</button>':'<span class="badge">'+esc(status)+'</span>')+prioridade+'</div>'});$('pcfisContainer').innerHTML=html||'<div class="empty">Nenhuma PCFI disponível para este usuário.</div>';var nova=$('pcfisContainer').querySelector('[data-nova-pcfi]');if(nova)nova.onclick=abrirNovaPcfi;Array.prototype.forEach.call($('pcfisContainer').querySelectorAll('[data-pcfi-i]'),function(b){b.onclick=function(){abrirPcfi(pcfis[Number(b.dataset.pcfiI)])}});Array.prototype.forEach.call($('pcfisContainer').querySelectorAll('[data-prioridade-i]'),function(b){b.onclick=function(){solicitarPrioridade(pcfis[Number(b.dataset.prioridadeI)])}})}
  async function solicitarPrioridade(pcfi){if(!confirm('Deseja solicitar prioridade para esta PCFI?'))return;loading(true,'Solicitando prioridade...');try{await apiSave({PRIORIDADE:'S'},'AD_PCFI',{NUPCFI:pcfi.NUPCFI});toast('Prioridade solicitada.');window.setTimeout(function(){window.location.reload()},900)}catch(e){toast('Falha ao solicitar prioridade: '+(e.message||e),true)}finally{loading(false)}}
  function prepararItens(base,salvos){return base.map(function(r){var antigo=salvos.filter(function(x){return String(x.SEQUENCIA)===String(r.SEQUENCIA)})[0]||{};return Object.assign({},r,antigo,{QTDRECEBIDA:antigo.QTDRECEBIDA||'',IMPROPRIO:antigo.IMPROPRIO||'N',QTDIMPROPRIA:antigo.QTDIMPROPRIA||0,DIVERGENCIA:antigo.DIVERGENCIA||'N',EMBALAGEM:antigo.EMBALAGEM||'I',MATERIAPRIMA:antigo.MATERIAPRIMA||'N',BEM:antigo.BEM||'N',OBSERVACAOPCFI:antigo.OBSERVACAOPCFI||'',lotes:[],patrimonios:[]})})}
  function abrirNovaPcfi(){state.pcfi=null;state.etapa='QTDE';state.itens=prepararItens(state.itensAll.filter(function(r){return String(r.NUNOTA)===String(state.pedido.NUNOTA)}),[]);mostrarConferencia();renderItens()}
  function abrirPcfi(pcfi){var etapa=etapaPcfi(pcfi);if(!podeEtapa(state.pedido,etapa)){toast('Você não está configurado para realizar a etapa de '+(etapa==='QUAL'?'qualidade':'análise fiscal')+'.',true);return}state.pcfi=pcfi;state.etapa=etapa;var base=state.itensAll.filter(function(r){return String(r.NUNOTA)===String(state.pedido.NUNOTA)}),salvos=state.itensPcfi.filter(function(r){return String(r.NUPCFI)===String(pcfi.NUPCFI)});state.itens=prepararItens(base,salvos);mostrarConferencia();renderItens()}
  function mostrarConferencia(){var etapa=state.etapa,nova=etapa==='QTDE';$('viewPcfis').hidden=true;$('viewPcfis').classList.add('hidden');$('viewConferencia').hidden=false;$('viewConferencia').classList.remove('hidden');$('pageTitle').textContent=(etapa==='QUAL'?'Qualidade':etapa==='FISC'?'Fiscal':'Quantidade')+' da '+(state.pcfi?'PCFI #'+state.pcfi.NUPCFI:'nova PCFI');$('pageSubtitle').textContent='Dados mantidos em memória até a confirmação do salvamento.';$('qualBadge').textContent=etapa==='QUAL'?'Qualidade':etapa==='FISC'?'Fiscal':'Quantidade';$('tituloConferencia').textContent=nova?'Identificação do recebimento':'Dados da PCFI';$('subtituloConferencia').textContent=nova?'O número da nota fiscal é obrigatório.':'Dados registrados na etapa de quantidade.';$('numNotaNf').value=nova?'':state.pcfi.NUMNOTANF;$('obsGeral').value=nova?'':state.pcfi.OBSERVACAO||'';$('numNotaNf').readOnly=!nova;$('obsGeral').readOnly=!nova;$('dadosRecebimento').classList.toggle('hidden',etapa==='FISC');$('btnSalvar').textContent=etapa==='FISC'?'Confirmar análise fiscal':etapa==='QUAL'?'Salvar qualidade':'Salvar conferência';contexto('ocContext')}
  function voltar(){state.pedido=null;state.pcfi=null;state.etapa='';state.itens=[];['viewConferencia','viewPcfis'].forEach(function(id){$(id).hidden=true;$(id).classList.add('hidden')});$('viewLista').hidden=false;$('viewLista').classList.remove('hidden');$('btnVoltar').hidden=true;$('btnVoltar').classList.add('hidden');$('btnAtualizar').classList.remove('hidden');$('pageTitle').textContent='Pedidos de Compra Pendentes';$('pageSubtitle').textContent='Duplo clique em um pedido para iniciar a conferência.'}
  function field(label,type,value,attrs){return '<label class="field"><span>'+label+'</span><input type="'+type+'" value="'+esc(value)+'" '+(attrs||'')+'></label>'}
  function renderItens(){
    var quality=state.etapa==='QUAL',readonly=state.etapa!=='QTDE';
    $('itensContainer').innerHTML=state.itens.map(function(it,i){return '<article class="item-card" data-item="'+i+'"><div class="item-head"><div><h3>'+esc(it.SEQUENCIA)+' · '+esc(it.CODPROD)+' — '+esc(it.DESCRPROD)+'</h3><p>Pedido: '+fmt(it.QTDNEG)+' '+esc(it.CODVOL)+' · Pendente: '+fmt(it.QTDPENDENTE)+' '+esc(it.CODVOL)+'</p></div></div><div class="item-grid">'+
      field('Quantidade recebida *','number',it.QTDRECEBIDA,'class="bind" data-k="QTDRECEBIDA" min="0" max="'+esc(it.QTDPENDENTE)+'" step="0.0001" '+(readonly?'readonly':'') )+
      (quality?'<div class="quality-grid"><label class="field"><span>Embalagem *</span><select class="bind" data-k="EMBALAGEM"><option value="I">Íntegra</option><option value="A">Avariada</option></select></label><label class="field"><span>Divergência *</span><select class="bind" data-k="DIVERGENCIA"><option value="N">Nenhuma</option><option value="E">Especificação</option><option value="Q">Quantidade</option><option value="A">Ambas</option></select></label><label class="checkline"><input type="checkbox" class="bind-check" data-k="IMPROPRIO"> Item impróprio</label><label class="field improper '+(it.IMPROPRIO==='S'?'':'hidden')+'"><span>Qtd. imprópria *</span><input type="number" class="bind" data-k="QTDIMPROPRIA" min="0" step="0.0001" value="'+esc(it.QTDIMPROPRIA)+'"></label><label class="checkline"><input type="checkbox" class="bind-check" data-k="MATERIAPRIMA"> Matéria-prima</label><label class="checkline"><input type="checkbox" class="bind-check" data-k="BEM"> Patrimônio</label><label class="field field-wide"><span>Observação do item</span><textarea class="bind" data-k="OBSERVACAOPCFI" rows="2" maxlength="4000">'+esc(it.OBSERVACAOPCFI)+'</textarea></label></div><div class="conditional lotes '+(it.MATERIAPRIMA==='S'?'':'hidden')+'"><div class="conditional-head"><div><strong>Lotes da matéria-prima</strong><p>Número, quantidade, fabricação e validade são obrigatórios.</p></div><button type="button" class="btn btn-secondary add-lote">Adicionar lote</button></div><div class="subrows lotes-rows"></div></div><div class="conditional pats '+(it.BEM==='S'?'':'hidden')+'"><div class="conditional-head"><div><strong>Patrimônios</strong><p>Informe um patrimônio por unidade recebida.</p></div><button type="button" class="btn btn-secondary add-pat">Adicionar patrimônio</button></div><div class="subrows pat-rows"></div></div>':'')+
      '</div></article>'}).join('');bindItens();state.itens.forEach(function(_,i){renderSubs(i)})
  }
  function bindItens(){Array.prototype.forEach.call(document.querySelectorAll('.item-card'),function(card){var i=Number(card.dataset.item);Array.prototype.forEach.call(card.querySelectorAll('.bind'),function(el){el.oninput=function(){state.itens[i][el.dataset.k]=el.value}});Array.prototype.forEach.call(card.querySelectorAll('.bind-check'),function(el){el.checked=state.itens[i][el.dataset.k]==='S';el.onchange=function(){state.itens[i][el.dataset.k]=el.checked?'S':'N';if(el.dataset.k==='IMPROPRIO')card.querySelector('.improper').classList.toggle('hidden',!el.checked);if(el.dataset.k==='MATERIAPRIMA'){card.querySelector('.lotes').classList.toggle('hidden',!el.checked);if(el.checked&&!state.itens[i].lotes.length)state.itens[i].lotes.push({NROLOTE:'',QUANTIDADE:state.itens[i].QTDRECEBIDA,DTFABRICACAO:'',DTVALIDADE:''});renderSubs(i)}if(el.dataset.k==='BEM'){card.querySelector('.pats').classList.toggle('hidden',!el.checked);if(el.checked&&!state.itens[i].patrimonios.length)state.itens[i].patrimonios.push({NROPATRIMONIO:''});renderSubs(i)}}});var al=card.querySelector('.add-lote'),ap=card.querySelector('.add-pat');if(al)al.onclick=function(){state.itens[i].lotes.push({NROLOTE:'',QUANTIDADE:'',DTFABRICACAO:'',DTVALIDADE:''});renderSubs(i)};if(ap)ap.onclick=function(){state.itens[i].patrimonios.push({NROPATRIMONIO:''});renderSubs(i)}})}
  function renderSubs(i){var card=document.querySelector('.item-card[data-item="'+i+'"]'),it=state.itens[i];if(!card)return;var lr=card.querySelector('.lotes-rows'),pr=card.querySelector('.pat-rows');if(lr){lr.innerHTML=it.lotes.map(function(l,j){return '<div class="subrow" data-j="'+j+'">'+field('Número do lote *','text',l.NROLOTE,'data-lk="NROLOTE" maxlength="60"')+field('Quantidade *','number',l.QUANTIDADE,'data-lk="QUANTIDADE" min="0" step="0.0001"')+field('Fabricação *','date',l.DTFABRICACAO,'data-lk="DTFABRICACAO"')+field('Validade *','date',l.DTVALIDADE,'data-lk="DTVALIDADE"')+'<button type="button" class="icon-btn">Remover</button></div>'}).join('');Array.prototype.forEach.call(lr.querySelectorAll('.subrow'),function(row){var j=Number(row.dataset.j);Array.prototype.forEach.call(row.querySelectorAll('[data-lk]'),function(el){el.oninput=function(){it.lotes[j][el.dataset.lk]=el.value}});row.querySelector('.icon-btn').onclick=function(){it.lotes.splice(j,1);renderSubs(i)}})}if(pr){pr.innerHTML=it.patrimonios.map(function(p,j){return '<div class="subrow pat-row" data-j="'+j+'">'+field('Número do patrimônio *','text',p.NROPATRIMONIO,'data-pk="NROPATRIMONIO" maxlength="60"')+'<button type="button" class="icon-btn">Remover</button></div>'}).join('');Array.prototype.forEach.call(pr.querySelectorAll('.pat-row'),function(row){var j=Number(row.dataset.j),el=row.querySelector('[data-pk]');el.oninput=function(){it.patrimonios[j].NROPATRIMONIO=el.value};row.querySelector('.icon-btn').onclick=function(){it.patrimonios.splice(j,1);renderSubs(i)}})}}
  function validar(){
    var errors=[];if(!$('numNotaNf').value.trim())errors.push('Informe o número da nota fiscal.');var ativos=state.itens.filter(function(it){return n(it.QTDRECEBIDA)>0});if(!ativos.length)errors.push('Informe quantidade recebida em ao menos um item.');var quality=state.etapa==='QUAL';
    ativos.forEach(function(it){if(state.etapa==='QTDE'&&n(it.QTDRECEBIDA)>n(it.QTDPENDENTE))errors.push('Item '+it.SEQUENCIA+': quantidade recebida maior que a pendente.');if(!quality)return;if(it.IMPROPRIO==='S'&&(n(it.QTDIMPROPRIA)<=0||n(it.QTDIMPROPRIA)>n(it.QTDRECEBIDA)))errors.push('Item '+it.SEQUENCIA+': quantidade imprópria inválida.');if(it.MATERIAPRIMA==='S'){if(!it.lotes.length)errors.push('Item '+it.SEQUENCIA+': adicione ao menos um lote.');var soma=0;it.lotes.forEach(function(l){soma+=n(l.QUANTIDADE);if(!l.NROLOTE.trim()||n(l.QUANTIDADE)<=0||!l.DTFABRICACAO||!l.DTVALIDADE)errors.push('Item '+it.SEQUENCIA+': preencha todos os campos dos lotes.');if(l.DTFABRICACAO&&l.DTVALIDADE&&l.DTVALIDADE<l.DTFABRICACAO)errors.push('Item '+it.SEQUENCIA+': validade anterior à fabricação.');});if(Math.abs(soma-n(it.QTDRECEBIDA))>.0001)errors.push('Item '+it.SEQUENCIA+': soma dos lotes difere da quantidade recebida.')}if(it.BEM==='S'){if(it.patrimonios.length!==n(it.QTDRECEBIDA))errors.push('Item '+it.SEQUENCIA+': patrimônios devem corresponder à quantidade recebida.');it.patrimonios.forEach(function(p){if(!p.NROPATRIMONIO.trim())errors.push('Item '+it.SEQUENCIA+': informe todos os patrimônios.')})}});return {errors:errors,ativos:ativos}
  }
  async function salvar(){
    if(!cfg.codUsu){toast('Código do usuário logado não foi disponibilizado pelo gadget.',true);return}
    if(state.etapa==='FISC'){var aprovada=confirm('O Fiscal confirma as operações desta PCFI?\nOK: autorizar para lançamento.\nCancelar: não autorizar.');loading(true,'Salvando análise fiscal...');$('btnSalvar').disabled=true;try{await apiSave({STATUSPCFI:'C',STATUSFISCAL:aprovada?'A':'N',RESULTADOPCFI:aprovada?'A':'N',CODUSUFISC:cfg.codUsu,DHCONCFISC:new Date().toISOString()},'AD_PCFI',{NUPCFI:state.pcfi.NUPCFI});toast('Análise fiscal '+(aprovada?'autorizada':'não autorizada')+'.');window.setTimeout(function(){window.location.reload()},900)}catch(e){toast('Falha na análise fiscal: '+(e.message||e),true)}finally{loading(false);$('btnSalvar').disabled=false}return}
    var v=validar();if(v.errors.length){toast(v.errors[0]+(v.errors.length>1?' (e mais '+(v.errors.length-1)+' pendência(s))':''),true);return}if(!confirm('Confirma o salvamento definitivo desta conferência?'))return;loading(true,'Salvando PCFI...');$('btnSalvar').disabled=true;
    try{
      var nupcfi=state.pcfi&&state.pcfi.NUPCFI,parcial=v.ativos.length<state.itens.length||v.ativos.some(function(it){return n(it.QTDRECEBIDA)<n(it.QTDPENDENTE)}),q=state.etapa==='QUAL';
      if(!nupcfi){if(state.pcfis.some(function(p){return String(p.NUNOTAOC)===String(state.pedido.NUNOTA)&&String(p.NUMNOTANF)===String($('numNotaNf').value.trim())}))throw new Error('Já existe uma PCFI para esta nota fiscal e OC.');var h=await apiSave({CODEMP:state.pedido.CODEMP,NUNOTAOC:state.pedido.NUNOTA,NUMNOTANF:$('numNotaNf').value.trim(),CODPARC:state.pedido.CODPARC,CODCENCUS:state.pedido.CODCENCUS,STATUSPCFI:'Q',STATUSQUAL:'P',STATUSFISCAL:'P',RESULTADOPCFI:'P',PRIORIDADE:'N',ENTREGAPARCIAL:parcial?'S':'N',OBSERVACAO:$('obsGeral').value.trim(),CODUSUINC:cfg.codUsu,CODUSUQTDE:cfg.codUsu,DHCONCQTDE:new Date().toISOString()},'AD_PCFI',null,['NUPCFI']);nupcfi=h.NUPCFI;if(!nupcfi)throw new Error('A inclusão de AD_PCFI não retornou NUPCFI.');for(var x=0;x<v.ativos.length;x++){var it=v.ativos[x],ir=await apiSave({NUPCFI:nupcfi,NUNOTAOC:it.NUNOTA,SEQITEMOC:it.SEQUENCIA,CODPROD:it.CODPROD,QTDRECEBIDA:n(it.QTDRECEBIDA),IMPROPRIO:'N',QTDIMPROPRIA:0,DIVERGENCIA:'N',EMBALAGEM:'I',MATERIAPRIMA:'N',BEM:'N',OBSERVACAO:''},'AD_PCFIITE',null,['SEQUENCIA']);if(!ir.SEQUENCIA)throw new Error('O item '+it.SEQUENCIA+' não retornou SEQUENCIA.')}}
      else if(q){await apiSave({STATUSPCFI:'F',STATUSQUAL:'A',CODUSUQUAL:cfg.codUsu,DHCONCQUAL:new Date().toISOString()},'AD_PCFI',{NUPCFI:nupcfi});for(var y=0;y<v.ativos.length;y++){var qi=v.ativos[y];await apiSave({IMPROPRIO:qi.IMPROPRIO,QTDIMPROPRIA:qi.IMPROPRIO==='S'?n(qi.QTDIMPROPRIA):0,DIVERGENCIA:qi.DIVERGENCIA,EMBALAGEM:qi.EMBALAGEM,MATERIAPRIMA:qi.MATERIAPRIMA,BEM:qi.BEM,OBSERVACAO:qi.OBSERVACAOPCFI},'AD_PCFIITE',{NUPCFI:nupcfi,SEQUENCIA:qi.SEQPCFIITEM})}}
      toast('PCFI '+nupcfi+' salva com sucesso.');window.setTimeout(function(){window.location.reload()},900);
    }catch(e){toast('Falha no salvamento: '+(e.message||e)+'. Consulte o PCFI antes de tentar novamente.',true)}finally{loading(false);$('btnSalvar').disabled=false}
  }
  $('btnAtualizar').onclick=carregarPedidos;$('btnVoltar').onclick=voltar;$('btnVoltarPcfis').onclick=voltar;$('btnCancelar').onclick=function(){abrirPedido(state.pedido)};$('btnSalvar').onclick=salvar;$('btnPaginaAnterior').onclick=function(){if(state.paginaPedidos>1){state.paginaPedidos--;renderPedidos(state.pedidosFiltrados)}};$('btnProximaPagina').onclick=function(){var totalPaginas=Math.ceil(state.pedidosFiltrados.length/state.pedidosPorPagina);if(state.paginaPedidos<totalPaginas){state.paginaPedidos++;renderPedidos(state.pedidosFiltrados)}};$('buscaPedidos').oninput=function(){var q=this.value.toLowerCase();state.paginaPedidos=1;state.pedidosFiltrados=state.pedidos.filter(function(r){return [r.NUNOTA,r.NUMNOTA,r.CODPARC,r.NOMEPARC,r.CODCENCUS].join(' ').toLowerCase().indexOf(q)>=0});renderPedidos(state.pedidosFiltrados)};carregarPedidos();
})();