<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" errorPage="erro.jsp" %>
<%@ taglib uri="http://java.sun.com/jstl/core_rt" prefix="c" %>
<%@ taglib prefix="snk" uri="/WEB-INF/tld/sankhyaUtil.tld" %>

<snk:query var="pcfiPedidos" dataSource="MGEDS">
SELECT
      C.NUNOTA
    , C.NUMNOTA
    , CONVERT(VARCHAR(10), C.DTNEG, 103) AS DTNEG
    , C.CODEMP
    , C.CODPARC
    , P.NOMEPARC
    , C.CODCENCUS
    , CONCAT(C.CODCENCUS, ' - ', CR.DESCRCENCUS) AS DESCRCR
    , C.CODTIPOPER
    , ISNULL(ITENS.QTD_ITENS, 0) AS QTD_ITENS
    , ISNULL(ITENS.QTD_PENDENTE, 0) AS QTD_PENDENTE
    , ISNULL(ITENS.QTD_PCFI, 0) AS QTD_PCFI
    , ISNULL(CFG.QUALPELCONF, 'N') AS QUALPELCONF
    , LOGADO.CODUSU AS CODUSULOGADO
    , CASE WHEN EXISTS (
          SELECT 1
            FROM TSIPAR PAR
           WHERE PAR.CHAVE = 'USUPRIORPCFI'
             AND ',' + REPLACE(ISNULL(PAR.TEXTO, ''), ' ', '') + ',' LIKE '%,' + CONVERT(VARCHAR(20), LOGADO.CODUSU) + ',%'
      ) THEN 'S' ELSE 'N' END AS PODEPRIORIDADE
    , CASE WHEN CFG.NUCONFIG IS NOT NULL
              AND ISNULL(CFG.PERMQUAL, 'N') = 'N'
              AND (EXISTS (SELECT 1 FROM TSIUSU U WHERE U.CODUSU = LOGADO.CODUSU AND U.CODGRUPO = CFG.CODGRUPOQTDE)
                   OR USUCFG.CODUSU IS NOT NULL)
           THEN 'S' ELSE 'N' END AS PODEQTDE
    , CASE WHEN CFG.NUCONFIG IS NOT NULL
              AND (ISNULL(CFG.PERMQUAL, 'N') = 'S'
                   OR (ISNULL(CFG.PERMQUAL, 'N') = 'N' AND ISNULL(CFG.QUALPELCONF, 'N') = 'S'))
              AND (EXISTS (SELECT 1 FROM TSIUSU U WHERE U.CODUSU = LOGADO.CODUSU AND U.CODGRUPO = CFG.CODGRUPOQUAL)
                   OR USUCFG.CODUSU IS NOT NULL)
           THEN 'S' ELSE 'N' END AS PODEQUAL
    , CASE WHEN CFG.NUCONFIG IS NOT NULL
              AND EXISTS (SELECT 1 FROM TSIUSU U WHERE U.CODUSU = LOGADO.CODUSU AND U.CODGRUPO = CFG.CODGRUPOFISC)
           THEN 'S' ELSE 'N' END AS PODEFISC
    , CASE WHEN ISNULL(ITENS.QTD_PENDENTE, 0) <= 0 THEN 'Quantidade concluída'
           WHEN ISNULL(ITENS.QTD_PCFI, 0) > 0 THEN 'Quantidade Parcial'
           ELSE 'Aguardando Quantidade' END AS STATUSOC
FROM TGFCAB C
INNER JOIN TGFPAR P ON P.CODPARC = C.CODPARC
LEFT JOIN TSICUS CR ON CR.CODCENCUS = C.CODCENCUS
CROSS JOIN (SELECT COALESCE(NULLIF(sankhya.STP_GET_CODUSULOGADO(), 0), ${CODUSU_LOG}) AS CODUSU) LOGADO
OUTER APPLY (
    SELECT TOP 1 X.NUCONFIG, X.QUALPELCONF, X.CODGRUPOQTDE, X.CODGRUPOQUAL, X.CODGRUPOFISC, X.PERMQUAL
      FROM AD_PCFICFG X
     WHERE X.CODCENCUS = C.CODCENCUS
       AND X.ATIVO = 'S'
       AND (X.CODTIPOPER IS NULL OR X.CODTIPOPER = C.CODTIPOPER)
     ORDER BY CASE WHEN X.CODTIPOPER = C.CODTIPOPER THEN 0 ELSE 1 END, X.NUCONFIG
) CFG
LEFT JOIN AD_PCFICFGUSU USUCFG ON USUCFG.NUCONFIG = CFG.NUCONFIG AND USUCFG.CODUSU = LOGADO.CODUSU
OUTER APPLY (
    SELECT COUNT(*) AS QTD_ITENS
         , SUM(CASE WHEN I.QTDNEG - I.QTDENTREGUE - I.QTDCONFERIDA - ISNULL(PCFIITEM.QTD_PCFI, 0) > 0
                    THEN I.QTDNEG - I.QTDENTREGUE - I.QTDCONFERIDA - ISNULL(PCFIITEM.QTD_PCFI, 0) ELSE 0 END) AS QTD_PENDENTE
         , SUM(ISNULL(PCFIITEM.QTD_PCFI, 0)) AS QTD_PCFI
      FROM TGFITE I
      OUTER APPLY (
          SELECT SUM(PI.QTDRECEBIDA) AS QTD_PCFI
            FROM AD_PCFIITE PI
            INNER JOIN AD_PCFI H ON H.NUPCFI = PI.NUPCFI AND H.STATUSPCFI <> 'X'
           WHERE PI.NUNOTAOC = I.NUNOTA AND PI.SEQITEMOC = I.SEQUENCIA
      ) PCFIITEM
     WHERE I.NUNOTA = C.NUNOTA AND I.PENDENTE = 'S'
) ITENS
WHERE C.TIPMOV = 'O'
  AND ITENS.QTD_ITENS > 0
  AND C.CODEMP IN (:P_CODEMP)
  AND C.DTNEG >= CONVERT(DATE, :P_DTINI)
  AND C.DTNEG < DATEADD(DAY, 1, CONVERT(DATE, :P_DTFIM))
  AND (C.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
  AND (C.NUNOTA = :P_NUNOTAOC OR :P_NUNOTAOC IS NULL)
ORDER BY C.DTNEG DESC, C.NUNOTA DESC
</snk:query>
<c:set scope="request" var="pcfiPedidosApp" value="${pcfiPedidos}" />

<snk:query var="pcfiItens" dataSource="MGEDS">
SELECT
      I.NUNOTA
    , I.SEQUENCIA
    , I.CODPROD
    , P.DESCRPROD
    , I.CODVOL
    , I.QTDNEG
    , CASE WHEN I.QTDNEG - I.QTDENTREGUE - I.QTDCONFERIDA - ISNULL(PCFIITEM.QTD_PCFI, 0) > 0
           THEN I.QTDNEG - I.QTDENTREGUE - I.QTDCONFERIDA - ISNULL(PCFIITEM.QTD_PCFI, 0) ELSE 0 END AS QTDPENDENTE
    , I.QTDENTREGUE
    , I.OBSERVACAO
FROM TGFCAB C
INNER JOIN TGFITE I ON I.NUNOTA = C.NUNOTA
INNER JOIN TGFPRO P ON P.CODPROD = I.CODPROD
OUTER APPLY (
    SELECT SUM(PI.QTDRECEBIDA) AS QTD_PCFI
      FROM AD_PCFIITE PI
      INNER JOIN AD_PCFI H ON H.NUPCFI = PI.NUPCFI AND H.STATUSPCFI <> 'X'
     WHERE PI.NUNOTAOC = I.NUNOTA AND PI.SEQITEMOC = I.SEQUENCIA
) PCFIITEM
WHERE C.TIPMOV = 'O'
  AND I.PENDENTE = 'S'
  AND C.CODEMP IN (:P_CODEMP)
  AND C.DTNEG >= CONVERT(DATE, :P_DTINI)
  AND C.DTNEG < DATEADD(DAY, 1, CONVERT(DATE, :P_DTFIM))
  AND (C.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
  AND (C.NUNOTA = :P_NUNOTAOC OR :P_NUNOTAOC IS NULL)
ORDER BY I.NUNOTA, I.SEQUENCIA
</snk:query>
<c:set scope="request" var="pcfiItensApp" value="${pcfiItens}" />

<snk:query var="pcfiRegistros" dataSource="MGEDS">
SELECT H.NUPCFI, H.NUNOTAOC, H.NUMNOTANF, H.STATUSPCFI, H.STATUSQUAL, H.STATUSFISCAL, H.PRIORIDADE, H.ENTREGAPARCIAL, H.OBSERVACAO
  FROM AD_PCFI H
  INNER JOIN TGFCAB C ON C.NUNOTA = H.NUNOTAOC
 WHERE H.STATUSPCFI <> 'X'
   AND C.TIPMOV = 'O'
   AND C.CODEMP IN (:P_CODEMP)
   AND C.DTNEG >= CONVERT(DATE, :P_DTINI)
   AND C.DTNEG < DATEADD(DAY, 1, CONVERT(DATE, :P_DTFIM))
   AND (C.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
   AND (C.NUNOTA = :P_NUNOTAOC OR :P_NUNOTAOC IS NULL)
 ORDER BY H.NUNOTAOC, H.NUPCFI DESC
</snk:query>
<c:set scope="request" var="pcfiRegistrosApp" value="${pcfiRegistros}" />

<snk:query var="pcfiItensRegistrados" dataSource="MGEDS">
SELECT PI.NUPCFI, PI.SEQUENCIA AS SEQPCFIITEM, PI.NUNOTAOC, PI.SEQITEMOC, PI.CODPROD, PI.QTDRECEBIDA, PI.IMPROPRIO, PI.QTDIMPROPRIA, PI.DIVERGENCIA, PI.EMBALAGEM, PI.MATERIAPRIMA, PI.BEM, PI.OBSERVACAO
  FROM AD_PCFIITE PI
  INNER JOIN AD_PCFI H ON H.NUPCFI = PI.NUPCFI AND H.STATUSPCFI <> 'X'
  INNER JOIN TGFCAB C ON C.NUNOTA = PI.NUNOTAOC
 WHERE C.TIPMOV = 'O'
   AND C.CODEMP IN (:P_CODEMP)
   AND C.DTNEG >= CONVERT(DATE, :P_DTINI)
   AND C.DTNEG < DATEADD(DAY, 1, CONVERT(DATE, :P_DTFIM))
   AND (C.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
   AND (C.NUNOTA = :P_NUNOTAOC OR :P_NUNOTAOC IS NULL)
</snk:query>
<c:set scope="request" var="pcfiItensRegistradosApp" value="${pcfiItensRegistrados}" />